version: '3.8'

services:
  # TT-CableGen Flask Application
  tt-cablegen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tt-cablegen-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server.py
    networks:
      - tt-cablegen-network
    volumes:
      # Mount any persistent data directories if needed
      - cablegen-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy with ACME Support
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: tt-cablegen-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VAULT_ACME_DIRECTORY_URL=${VAULT_ACME_DIRECTORY_URL:-https://vault.tenstorrent.com/v1/pki/acme/directory}
      - VAULT_ACME_CONTACT=${VAULT_ACME_CONTACT:-it@tenstorrent.com}
      - TT_FQDN=${TT_FQDN:-cablegen.tenstorrent.com}
    volumes:
      - nginx-acme-cache:/var/cache/nginx/acme-vault
      - nginx-logs:/var/log/nginx
    networks:
      - tt-cablegen-network
    depends_on:
      tt-cablegen:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  tt-cablegen-network:
    driver: bridge
    name: tt-cablegen-network

volumes:
  cablegen-data:
    name: tt-cablegen-data
  nginx-acme-cache:
    name: tt-cablegen-nginx-acme-cache
  nginx-logs:
    name: tt-cablegen-nginx-logs
