# CableGen Docker Compose Configuration
#
# This compose file sets up a complete CableGen deployment with:
# - CableGen Flask application (port 5000 internal)
# - Nginx reverse proxy with ACME certificate support (ports 80/443 external)
# - Automatic SSL certificate provisioning via Vault ACME
# - Persistent volumes for data and certificate cache
#
# Usage:
#   make setup    # Copy env.example to .env and configure
#   make build    # Build all Docker images
#   make up       # Start all services
#   make logs     # View service logs
#   make status   # Check service status
#
# Environment Variables (set in .env):
#   VAULT_ACME_DIRECTORY_URL - Vault ACME directory endpoint
#   VAULT_ACME_CONTACT       - Contact email for ACME certificates
#   FQDN                     - Fully qualified domain name for certificates
#
# The Nginx service automatically provisions SSL certificates and redirects
# all HTTP traffic to HTTPS. All requests are reverse-proxied to the Flask app.

version: '3.8'

services:
  # Tenstorrent CableGen Flask Application
  cablegen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cablegen-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server.py
    networks:
      - cablegen-network


  # Nginx Reverse Proxy with ACME Support
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cablegen-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VAULT_ACME_DIRECTORY_URL=${VAULT_ACME_DIRECTORY_URL:-https://vault.yourcompany.com/v1/pki/acme/directory}
      - VAULT_ACME_CONTACT=${VAULT_ACME_CONTACT:-it@yourcompany.com}
      - FQDN=${FQDN:-cablegen.yourcompany.com}
    volumes:
      - nginx-acme-cache:/var/cache/nginx/acme-vault
      - nginx-logs:/var/log/nginx
    networks:
      - cablegen-network
    depends_on:
      cablegen:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  cablegen-network:
    driver: bridge
    name: cablegen-network

volumes:
  nginx-acme-cache:
    name: cablegen-nginx-acme-cache
  nginx-logs:
    name: cablegen-nginx-logs
